apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: health-service
  name: health-service
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: health-service
  type: ClusterIP
